---

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ticketsale_db
        username: ticketsale
        password: ticketsale
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate: org.hibernate.dialect.MySQL5Dialect

...